### ISSUE TITLE
Crear pantalla de iniciar sesion e integrar con firebase

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/air-flashcards#11]
El objetivo es crear otra page que sea para iniciar sesion. No es necesario que la pagina tenga estilos, el objetivo es utilizar los conocimientos en la charla de hoy: crear una pagina en next, usar los componentes del formulario de registro, integrar el metodo signin de firebase.

## Criterios de aceptacion
1. El usuario debe poder loggearse con email y contraseña
2. Se debe validar el usuario contra firebase
3. Se debe dar feedback al usuario a traves de alerts sobre el resultado (campos vacios, loggeado, error)

Documentacion adicional:

Consola del proyecto (Si no tenes acceso solicitanos por el canal de air-proyect de Discord!):
https://console.firebase.google.com/u/0/project/air-flashcards/overview

Integrar firebase: 
https://firebase.google.com/docs/auth/web/password-auth#sign_in_a_user_with_an_email_address_and_password

Conventional commits:
https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by dafnecaneda** [comment]
Creo que ya lo pude hacer: 

`const handleSubmitLogin: FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault();

    const {email, password } = state;

    if (!password || !email) {
      window.alert("Please fill all fields");
      return;
    }
  
    const user = await logIn(email, password);
    if (user) {
      window.alert("User logged");
      console.log(user);
    } else {
      window.alert("Unable to login");
    }
  };`

**Comment by dafnecaneda** [comment]
`const handleSubmitLogin: FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault();

    const {email, password } = state;

    if (!password || !email) {
      window.alert("Please fill all fields");
      return;
    }
  
    const user = await logIn(email, password);
    if (user) {
      window.alert("User logged");
      console.log(user);
    } else {
      window.alert("Unable to login");
    }
  };`

**Comment by dafnecaneda** [comment]
```
import { getAuth, signInWithEmailAndPassword, signOut } from "firebase/auth";

const auth = getAuth();

export const logIn = async (email: string, password: string) => {
  try {
    const user = await signInWithEmailAndPassword(auth, email, password)
    return user; 
  } catch (error) {
    console.error(error);
  }
};
```

**Comment by dafnecaneda** [comment]
la consola devuelve: 

UserCredentialImpl {user: UserImpl, providerId: null, _tokenResponse: {…}, operationType: 'signIn'}
operationType: "signIn"
providerId: null
user: UserImpl {providerId: 'firebase', proactiveRefresh: ProactiveRefresh, reloadUserInfo: {…}, reloadListener: null, uid: '1ahNZgCeHOglYr4CT6E1MDpZcnH2', …}
_tokenResponse: {kind: 'identitytoolkit#VerifyPasswordResponse', localId: '1ahNZgCeHOglYr4CT6E1MDpZcnH2', email: 'testing@123.com', displayName: '', idToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkMWIxOWYwZjU4ZTJjOW…B2bpJ9bY4AHR9mid2REp9XwaJn5fm63b69H84eXSLP9RlZAmg', …}
[[Prototype]]: Object

**Comment by tomi-mercado** [comment]
@dafnecaneda Buenísimo! Pero no veo el PR 🤔 . Paso nuevamente esto a la columna de In progress.

**Comment by tomi-mercado** [comment]
@dafnecaneda paso nuevamente a In progress porque no hay PR

**Comment by dafnecaneda** [comment]
Ahi ya hice el pull request pero espero qeu me ocnfirmes si llego asi lo paso a pull request aca tmb
