### ISSUE TITLE
Crear metodo para cerrar sesion con Firebase

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/air-flashcards#15]
Integrar la funcionalidad de firebase para cerrar sesion.

## Criterios de aceptacion
1. Dejar en el servicio de firebase una funcion a utilizar para cerrar sesion

## Links utiles
Nuestra consola de firebase:
https://console.firebase.google.com/u/0/project/air-flashcards/overview

Doc sobre como cerrar sesion:
https://firebase.google.com/docs/auth/web/password-auth#next_steps

**Comment by tomi-mercado** [comment]
@iarabaya @dafnecaneda cómo vienen con esto? necesitan una mano?

**Comment by iarabaya** [comment]
Hola! si, una duda, https://firebase.google.com/docs/auth/web/password-auth?hl=es-419 aca la documentacion no aclara si hay respuesta alguna del cierre de sesion con signOut, deberia entonces simplemente ponerle validaciones y tambien devolver yo una respuesta? Que recomendarias en este caso? Gracias

**Comment by dafnecaneda** [comment]
Hola @iarabaya, ya resolvi este issue y lo pante para PR, en el chat de peacocks subi los screenshots de como lo resolvi pero igualmente si necesitas que te explique avisame.

**Comment by iarabaya** [comment]
genial @dafnecaneda! Soy team flamingos pero cuando pueda lo chusmeo! y cualquier cosa te consulto en main jaja
