### ISSUE TITLE
Integrar autenticacion del frontend con las llamadas a firestore

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/air-flashcards#49]
## Contexto
Necesitamos autenticar las requests que le hacemos a firestore. Debemos tomar el token del usuario autenticado e implementarlo en una funcion generica que despues se utilize para hacer las peticiones de informacion a firestore.

## Criterios de aceptacion
1. Se debe integrar el usuario loggeado con las peticiones a firestore.
2. Se debe dejar un metodo generico para agregar las credenciales en cada request

## Links utiles
Si tessirve dejo la documentacion sobre como realizar esto con firestore:
https://firebase.google.com/docs/firestore/security/overview

Nuestra consola de firebase:
https://console.firebase.google.com/u/0/project/air-flashcards/overview

**Comment by kevin-dev71** [comment]
1. Setear [Content-owner only access rule](https://firebase.google.com/docs/rules/basics#content-owner_only_access) en firestore

```js
service cloud.firestore {
  match /databases/{database}/documents {
    // Allow only authenticated content owners access
    match /some_collection/{userId}/{documents=**} {
      allow read, write: if request.auth != null && request.auth.uid == userId
    }
  }
}
```

3. Crear una funcion en React en Client Side para [obtener el token](https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients), este token sera enviado a Next API como header Authorization.

```ts
firebase.auth().currentUser.getIdToken(/* forceRefresh */ true).then(function(idToken) {
  // Send token to your backend via HTTPS
  // ...
}).catch(function(error) {
  // Handle error
});
```

4. Desde Next API crear un middleware que intercepte todos los request con Authorization token, decodificarlo y obtener el `uid` , este `uid` sera enviado a firebase para permitir el acceso a los `documents/collections` del usuario ya que las Rules son verificada por `request.uid`  ([documentacion](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_the_firebase_admin_sdk))

```ts
// idToken comes from the client app
getAuth()
  .verifyIdToken(idToken)
  .then((decodedToken) => {
    const uid = decodedToken.uid;
    // ...
  })
  .catch((error) => {
    // Handle error
  });
```

5. ya con eso validamos si el usuario es correcto o no para darle acceso a la lectura/escritura de una collection.


@9gustin confirmame si tiene sentido esto para implementarlo 😄

**Comment by 9gustin** [comment]
Y una consulta, si habilitamos la autenticacion en firebase ya solo toma el token del usuario autenticado? no hay que hacer nada cuando se hace una request o se instancia la db? 

Porque si es asi lo que estamos haciendo es una validacion de auth en nuestra api, lo cual es un doble check pero la pregunta era, si habilitamos la regla de auth en firestore y el usuario se loggea en nuestra app, puede traer recursos de firestore o necesita integrar un token mas ahi?

**Comment by mariodev9** [comment]
Si no me equivoco puede traer recursos de firestore. Se haría el doble check desde las reglas de firebase y luego con un método generico podemos obtener el uid del usuario autenticado para hacer todas las verificaciones que sean necesarias
