### ISSUE TITLE
Revisar endpoint PATCH de cards

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/air-flashcards#69]
## Contexto 
Ya esta desarrollado el modelo final de cards, deberiamos hacer pruebas de el endpoint patch, para ver si nos vamos a tener conflictos con las propiedades de tipo objeto(SideA, SideB).

**Comment by nicodeheza** [comment]
Ahi lo probe. Básicamente si funciona como PATCH pero, obviamente si queres editar un objeto, por ejemplo sideA, tenes que pasar el nuevo objeto entero. Yo creo que no tiene sentido convertirlo en un PUT y tener que pasar el total del objeto. Creo que se se entiende que sideA es un campo y que lo tenes que pasar entero.

**Comment by nicodeheza** [comment]
Lo que si se podria hacer es agregar la validación del body  y  refactorizar el archivo para que no quede tan grande

**Comment by 9gustin** [comment]
De una! por ahora no refactorizaria, genial si anda como mencionas 😄

**Comment by nicodeheza** [comment]
Cierro la issue entonces
